### ISSUE TITLE
Complete reservations mock page

### ISSUE THREAD

**Issue by bra-alex** [Rent-Wheels/rent_wheels_user#13]
All the work for the car image and whatever is under it should be done in the `reservation_information_sections_widget.dart` file.

All new custom widgets you create must be placed in the widgets folder `lib>src>mainSection>reservations >widgets`.

The skeleton for the reservations page is in `screen_implementer.dart`.

There is a Sizes() class for setting width and height using MediaQuery, look through the code and use it where ever you need to set, width, height, padding, margin or border radius.

There is a Space() class for setting sized box heights. Use it instead of sized box when creating spaces.

There are set down text styles in `lib>core>widgets>textStyles`.

There is a generic button widget in `lib>core>widgets>buttons`. Use that instead of creating one

**Comment by bnakusaki1** [comment]
Aye aye
